// Catálogo LACA — datos de productos
// c = categoría | n = nombre | s = subtítulo/línea | b = beneficio | a = activos | p = presentación | pro = true si es SOLO uso profesional (gabinete)
const PRODUCTOS = [

// CUIDADOS BÁSICOS
{c:"Cuidados Básicos", n:"Sérum Demaquillante de Ojos y Labios", b:"Elimina maquillaje a prueba de agua sin irritar. Ideal para ojos sensibles.", a:"Siliconas volátiles, elastómero de siliconas, azuleno", p:"Frasco 70 ml"},
{c:"Cuidados Básicos", n:"Sérum Demaquillante Protector", b:"Sérum antiage que retira el maquillaje y protege el área de los párpados con vitamina E.", a:"Siliconas volátiles, Vitamina E", p:"Frasco 70 ml"},
{c:"Cuidados Básicos", n:"Leche de Limpieza", s:"con Fitoflavonas de Soja", b:"Elimina impurezas y maquillaje, humecta y atenúa el enrojecimiento.", a:"Extractos de avena, arroz, uva, regaliz, soja", p:"Frasco 100 ml"},
{c:"Cuidados Básicos", n:"Leche de Limpieza", s:"con Regaliz y activos vegetales", b:"Libera la piel de impurezas y exceso de oleosidad. Apta para pieles sensibles.", a:"Regaliz, aloe vera, ginseng, cola de caballo, manzanilla", p:"Frasco 100 / 250 / 500 ml"},
{c:"Cuidados Básicos", n:"Gel de Limpieza Protector", b:"Mantiene la piel libre de microorganismos. Para pieles acnéicas, grasas o seborreicas.", a:"Colágeno, aloe vera, manzanilla", p:"Frascos 100 / 250 ml"},
{c:"Cuidados Básicos", n:"Crema de Limpieza", s:"con Fitoesteroles de Soja y Malva", b:"Limpia en profundidad sin masaje excesivo, protege y descongestiona.", a:"Malva, regaliz, lanolina, fitoesteroles de soja, escualeno", p:"Pote 160 / 250 gr"},
{c:"Cuidados Básicos", n:"Dermopulido Gel", s:"con extractos frutales", b:"Acelera la renovación natural y prepara la piel para el tratamiento posterior.", a:"Polímero de nuez de Tagua, ácidos de arándano, caña de azúcar", p:"Pomo 70 g / Frasco 235 ml"},
{c:"Cuidados Básicos", n:"Scrub Facial", b:"Elimina impurezas y células muertas sin producir hiperemia.", a:"Micropartículas minerales, aloe vera, malva, hamamelis", p:"Pote 250 g"},
{c:"Cuidados Básicos", n:"Máscara Destello Vital", b:"Antioxidante cutáneo que mejora la microcirculación y devuelve luminosidad.", a:"Oligoelementos minerales, vitamina C, bentonita, caolín", p:"Pote 180 / 280 gr"},
{c:"Cuidados Básicos", n:"Brume Radiant", b:"Favorece la luminosidad, atenúa el enrojecimiento y reduce la hiperpigmentación.", a:"Lumiglow™ (Maqui Berry), Niacinamida, Regaliz", p:"Frascos 100 y 250 ml"},
{c:"Cuidados Básicos", n:"Aire Libre", s:"Repelente de insectos", b:"Repele insectos con protección de 5 horas. Amigable con piel y mascotas.", a:"IR3535®", p:"Frasco 100 ml"},

// DERMOCOSMÉTICA DR. ENERO
{c:"Dermocosmética Dr. Enero", n:"Monodosis Vitamina C Plus", b:"Piel más luminosa y joven con vitamina C estabilizada por tecnología enzimática.", a:"AA2G™, Hydrovance™", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Monodosis Hialurón Plus", b:"Mayor hidratación y relleno en arrugas profundas.", a:"4D Hyaluronic Acid, D-Pantenol", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Neodermis", s:"Ampollas de Elastina", b:"Tonifica y humecta en profundidad.", a:"Elastina, Colágeno Hidrolizado, PCA", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Piel Firm", s:"Ampollas de Colágeno", b:"Hidratan y disminuyen el enrojecimiento en todo tipo de pieles.", a:"Manzanilla, PCA, Colágeno", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Monodosis C", b:"Mantiene el balance hidrolipídico y combate radicales libres.", a:"Urea modificada, PCA, extracto de trébol rojo, vit. C y E", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Monodosis R", b:"Atenúa arrugas por acción del Argireline y devuelve aspecto joven.", a:"Argireline, gluconato de magnesio, ácido hialurónico", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Monodosis D", b:"Suaviza y atenúa el enrojecimiento por radicales libres y rayos UV.", a:"Ubiquinona, hialuronato de sodio, ginkgo biloba", p:"10 ampollas x 2 ml"},
{c:"Dermocosmética Dr. Enero", n:"Colágeno III", b:"Mejora la producción de colágeno joven, humectación y turgencia.", a:"Colágeno, dipalmitoil hidroxiprolina, provitamina B5", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Hialurón", b:"Voluminiza e hidrata todo tipo de pieles en forma inmediata.", a:"Ácido hialurónico, propilenglicol", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Sérum con DMAE", b:"Previene la flaccidez y mejora la apariencia de las arrugas.", a:"DMAE, Ácido Hialurónico", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Restaurador Epidérmico", b:"Recupera el Factor Natural de Humectación tras tratamientos intensos.", a:"Ácido Hialurónico, PCA, Liposomas de Colágeno", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Sérum Ionizable", s:"con Vitamina C", b:"Antioxidante y protector, ayuda a un aspecto firme y de color uniforme.", a:"Nanósferas de Vitamina C", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Óleo Multivitamínico", s:"con Rosa Mosqueta", b:"Repara el epitelio; útil también para cabello dañado, uñas y estrías.", a:"Alfa Bisabolol, Rosa Mosqueta, Vitamina A y C", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Gel Fortalecedor", s:"con Biotina", b:"Mejora el crecimiento de uñas débiles y estimula pestañas y cejas.", a:"Biotina, Alantoína", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Ablandador Enzimático", b:"Ablanda la epidermis facilitando las extracciones. pH neutro.", a:"Propylene glycol, Perfection Péptide P3™, Urea", p:"Frasco 250 ml"},
{c:"Dermocosmética Dr. Enero", n:"Loción con Agentes Sanitizantes", s:"de acción prolongada", b:"Bactericida y fungicida, acondiciona la piel antes y después del tratamiento.", a:"Alcohol desnaturalizado, Cloruro de Benzalconio", p:"Frasco 250 ml"},
{c:"Dermocosmética Dr. Enero", n:"Sérum Lifting Tensor", b:"Efecto tensor inmediato en el contorno de ojos, promueve colágeno.", a:"Isoflavonas de soja, Ácido Hialurónico", p:"Frasco 15 ml"},
{c:"Dermocosmética Dr. Enero", n:"Sérum Radiant Filler", b:"Rellena arrugas y depresiones, da luminosidad y previene manchas.", a:"Ácido Hialurónico 4D, Vitamina C", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Sérum Radiant Glow", b:"Mejora la luminosidad e iguala el tono de todo tipo de pieles.", a:"Lumiglow™, Nicotinamida", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Vital Booster", s:"Hylu-Serum", b:"Reduce el inflammaging y fortalece los cuatro pilares del cuidado cutáneo.", a:"Vitamina B12, Pantenol (B5), Niacinamida (B3)", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"AZ Booster", b:"Otorga radiancia, disminuye manchas y unifica el tono facial.", a:"iWhite PAD™, Nicotinamida, Pantenol, Lumiglow™", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Serum Calmer", b:"Mejora pieles sensibles e hiperactivas con desigualdad de tono.", a:"CALMandrin™, Pantenol, Ácido Hialurónico", p:"Gotero 20 ml"},
{c:"Dermocosmética Dr. Enero", n:"Serum Novo Retinol", b:"Retinol de origen vegetal, potencia proteínas estructurales sin enrojecer.", a:"NovoRetin™, BakuLipid®, Vitamina B5", p:"Gotero 20 ml"},

// PIELES DELICADAS
{c:"Pieles Delicadas", n:"Sérum Humectante Herbal", b:"Controla el enrojecimiento y el ardor; calma tras peelings o extracciones.", a:"Aloe Vera, Manzanilla, Ginkgo, Ácido Hialurónico", p:"Frasco 70 ml"},
{c:"Pieles Delicadas", n:"Emulsión Humectante Herbal", b:"Rehidrata y repone pieles resecas, otorga frescura y suavidad.", a:"Aloe Vera, Manzanilla, Ginseng, Provitamina B5", p:"Frasco 100 ml"},
{c:"Pieles Delicadas", n:"Rocío Protector", s:"con Oligoelementos", b:"Calma y revitaliza tras dermoabrasión, peelings o radiofrecuencia.", a:"Urea, Manzanilla, Regaliz, Boswellia Serrata", p:"Frascos 100 / 250 ml"},
{c:"Pieles Delicadas", n:"Neblina Hidratante", s:"con Malva y Bosswelia", b:"Hidrata y suaviza, forma un escudo vegetal protector.", a:"Extractos de Malva, Boswelia, Tilo, Manzanilla", p:"Frascos 100 y 250 ml"},
{c:"Pieles Delicadas", n:"Emulsión Green Balance", b:"Evita la hipersensibilidad y mejora la circulación de capilares frágiles.", a:"Castaño de Indias, Vitamina C, Rutina", p:"Pomo 70 gr"},
{c:"Pieles Delicadas", n:"Máscara Descongestiva", s:"con Silanotriol y Vitamina B3", b:"Deja la piel fresca y luminosa, mejora el enrojecimiento.", a:"Regaliz, Aloe, Manzanilla, Nicotinamida", p:"Pote 250 gr"},
{c:"Pieles Delicadas", n:"Gel Humectante Herbal", b:"Combate el enrojecimiento producido por radiofrecuencia o exfoliantes.", a:"Glicerina, Ácido Hialurónico, Vitamina A y E", p:"Pote 250 gr"},
{c:"Pieles Delicadas", n:"Brume Calmer", b:"Protege el manto lípido y atenúa el enrojecimiento en todo tipo de piel.", a:"CALMandrin™, Ácido Hialurónico, Pantenol", p:"Frascos 100 / 250 ml"},

// ANTIAGE
{c:"Antiage", n:"Crema Células Madre", s:"con Octapéptidos y Argán", b:"Regenera profundamente y atenúa signos del tiempo. Para pieles maduras.", a:"PhytoCellTec Argan™, Snap 8™", p:"Pomo 70 gr"},
{c:"Antiage", n:"Bálsamo Dinamizante Celular", b:"Minimiza daños del estrés ambiental y mantiene la piel turgente. Para pieles jóvenes.", a:"DermCom™", p:"Pomo 70 gr"},
{c:"Antiage", n:"Emulsión Células Madre", b:"Retrasa el envejecimiento celular y redefine el óvalo facial.", a:"Phytocellmallus Domestica, isoflavonas de soja", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema", s:"con Oxígeno", b:"Disminuye arrugas mejorando el funcionamiento celular.", a:"Molécula de oxígeno saturada, Ácido Hialurónico", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema Liposomada", s:"con Ácido Hialurónico", b:"Redensifica, hidrata y nutre con rápido efecto visible.", a:"Ácido Hialurónico, Colágeno liposomado, Rosa mosqueta", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema Retinol", s:"con Vitamina C", b:"Reduce la profundidad de arrugas y recupera elasticidad.", a:"Retinol, Vitamina C estable, Provitamina B5", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema Retinol Plus", b:"Frena y retarda el envejecimiento, evita la flaccidez.", a:"Retinol, Vitamina A y E, Chitosan Reparador", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema Antiage Alimentar Nutrir", b:"Reconstituye y tonifica devolviendo salud y vigor a la piel.", a:"Coenzima Q, proteínas de suero, ginkgo biloba", p:"Pomo 70 gr"},
{c:"Antiage", n:"Film Crono Hidratante", b:"Forma una película que retiene la humedad y atenúa el aspecto marchito.", a:"Proteínas de suero, Elastina Hidrolizada, Coenzima Q", p:"Pomo 70 gr"},
{c:"Antiage", n:"Crema Antiage", s:"con Coenzima Q", b:"Repone defensas antioxidantes y mejora la elasticidad cutánea.", a:"Ubiquinona liposomada, Vitamina A, E, C y F", p:"Pomo 70 gr"},
{c:"Antiage", n:"Complejo Antiage", s:"con Omega Plus", b:"Acabado sedoso único, rehidratación natural.", a:"Vitaminas A, E y C, Retinol, Coenzima Q, Omega 3", p:"Pomo 50 gr"},
{c:"Antiage", n:"Biolifting XF", b:"Preserva la humedad y protege de agentes externos en pieles con signos de edad.", a:"Argireline, Ronacare, Ácido Fólico, Creatina", p:"Pomo 50 gr"},
{c:"Antiage", n:"Gel Contorno de Ojos", b:"Mejora e ilumina el área del ojo, disminuye arrugas y surcos.", a:"Manteca de Karité, Ácido Hialurónico, Colágeno Hidrolizado", p:"Pomo 15 gr"},
{c:"Antiage", n:"Secuencial Párpados", s:"Día y Noche", b:"Previene la formación de arrugas y mejora ojeras y bolsas.", a:"Día: Argireline, óxido de zinc / Noche: Vitamina A, péptidos", p:"2 pomos 15 gr"},
{c:"Antiage", n:"Fresh Eyes Roll On", s:"con Cafeína", b:"Efecto \"hielo\" refrescante y drenante, reduce signos de cansancio.", a:"Eyeseryl™, Cafeína", p:"Roll on 15 ml"},
{c:"Antiage", n:"Microfiller Antiage", b:"Efecto filler o microrrelleno en depresiones profundas.", a:"Ácido Hialurónico, Epidermosil™, Chronodyn™, Matrixyl™", p:"Roll on 15 ml"},
{c:"Antiage", n:"Crema Nutritiva de Párpados", b:"Previene arrugas profundas. Vegana, libre de parabenos y fragancias.", a:"Vitamina A y E, Eyeseryl™, Liposomas de Isoflavonas de Soja", p:"Frasco 10 ml"},
{c:"Antiage", n:"Diamond Lips", b:"Atenúa arrugas verticales del labio superior, madura las fibras de colágeno.", a:"Matrixyl Morphonics™, Ramnosa", p:"Gotero 12 ml"},
{c:"Antiage", n:"Diamond Eyes", b:"Corrige arrugas y líneas de expresión en la zona orbicular.", a:"ArgirelineTM, Snap-8™", p:"Gotero 12 ml"},
{c:"Antiage", n:"Filler Diamond Antiage", b:"Estimula la formación de ácido hialurónico propio de la piel.", a:"Novhyal™, Aquaxyl™, Ácido Hialurónico", p:"Frasco 30 ml"},
{c:"Antiage", n:"Cellular Diamond Antiage", b:"Activa procesos celulares que mejoran la longevidad de la piel.", a:"Snow Algae™, Ácido Hialurónico, Filtros Solares", p:"Frasco 60 gr"},
{c:"Antiage", n:"Renova Defense", b:"Recupera firmeza, vitalidad y luminosidad. Lentifica el envejecimiento.", a:"Renovage™, Liposomas de Isoflavonas de Soja", p:"Frasco 60 ml"},
{c:"Antiage", n:"Bio Therapy", s:"Hyalu-Serum", b:"5 péptidos que actúan como barrera contra arrugas de expresión.", a:"Munapsys, Mitellion, Telmeric, Breeztel, Col-Frag I", p:"Gotero 10 ml"},
{c:"Antiage", n:"Serum Liposomado", s:"con Ácido Hialurónico", b:"Regenera la barrera epidérmica dañada por sol o peeling.", a:"Ácido Pirrolidón Carbónico, Ácido Hialurónico", p:"Frasco 70 ml"},

// HIDRATACIÓN - HUMECTACIÓN - TONIFICACIÓN
{c:"Hidratación", n:"Loción Humectante y Tonificante", b:"Humecta y retiene la humedad por tiempo prolongado, previene el enrojecimiento.", a:"Colágeno, PCA, Boswellia, Regaliz, Hamamelis", p:"Frascos 100 / 250 / 500 ml"},
{c:"Hidratación", n:"Loción Refrescante", s:"con Té verde y Flavonoides", b:"Humecta y suaviza, aliada de la juventud y belleza de la piel.", a:"Uva, Té Verde, Avena", p:"Frascos 100 / 250 / 500 ml"},
{c:"Hidratación", n:"Emulsión Humectante Hidra Plus", b:"Triple eficacia hidratante, atenúa las arrugas.", a:"Regaliz, Rosa de Mosqueta, Aminoácidos, Ácido Hialurónico", p:"Frascos 100 / 250 ml"},
{c:"Hidratación", n:"Bruma Equilibrante", b:"Concentrado de activos refrescantes y reparadores epidérmicos.", a:"Avena, arroz, hamamelis, manzanilla, ginseng", p:"Frasco 100 ml"},
{c:"Hidratación", n:"Crema Hidratante", s:"con Urea +", b:"Repone el Factor Natural de Hidratación de la piel.", a:"Hidroxiethiel urea (urea+), lúpulo, caléndula, vitamina A", p:"Pote 250 gr"},
{c:"Hidratación", n:"Crema Humectante", s:"con Aceite de Palta", b:"Restaura la elasticidad y retarda el envejecimiento cutáneo.", a:"Lanolina, Aceite de Palta, Vitamina E, Colágeno", p:"Pote 160 gr"},
{c:"Hidratación", n:"Crema Color", s:"con Ácido Hialurónico", b:"Genera un color uniforme y brinda luminosidad. Para rostro y cuerpo.", a:"Colágeno, Ácido Hialurónico, perlas y colorantes", p:"Pomo 70 gr"},
{c:"Hidratación", n:"Hidrogel", s:"con Uniesferas de Vitaminas C y E", b:"Favorece la formación de colágeno y elastina.", a:"Vitamina C y E, Ácido Hialurónico, Pantenol", p:"Pomo 70 gr"},
{c:"Hidratación", n:"Crema Humectante", s:"con Aloe Vera", b:"Combate el enrojecimiento por sol o tratamientos cosméticos.", a:"Aloe Vera, Alantoína", p:"Pomo 140 gr"},
{c:"Hidratación", n:"Sérum Facial", s:"con Ramnosa", b:"Recupera el aspecto de una piel joven, repara colágeno y elastina.", a:"Sirhamnose™", p:"Frasco 70 ml"},
{c:"Hidratación", n:"Concentrado Hidroenergizante ACI", b:"Energizante y reparador, aporta componentes protectores y humectantes.", a:"Alanina, Prolina, Arginina, Ginseng", p:"Frascos 70 ml"},
{c:"Hidratación", n:"Máscara Radiant Filler", b:"Hidrata profundamente y produce efecto relleno en surcos y arrugas.", a:"Ácido Hialurónico 4D, Vitamina C estabilizada", p:"Pote 50 / 250 gr"},

// PIELES GRASAS
{c:"Pieles Grasas", n:"Lápiz Secativo", s:"con Tea Tree Oil", b:"Seca y descongestiona, disimula el enrojecimiento del acné.", a:"Óxido de zinc, Nicotinamida, Tea Tree Oil", p:"Lápiz 3,5 gr"},
{c:"Pieles Grasas", n:"Lápiz Secativo Incoloro", b:"Seca y descongestiona lesiones acneicas, sin producir irritación.", a:"Tea Tree Oil, Nicotinamida, Irgasan", p:"Lápiz 3,5 gr"},
{c:"Pieles Grasas", n:"Lápiz Secativo Color", b:"Seca las manifestaciones del acné, con color beige adaptable al tono de piel.", a:"Óxido de Zinc, Azufre Precipitado, Alcanfor", p:"Lápiz 3,5 gr"},
{c:"Pieles Grasas", n:"Crema Control Sebo", b:"Absorbe la grasitud superficial y combate la inflamación de los comedones.", a:"Microesfera Lipofílica", p:"Pomo 70 gr"},
{c:"Pieles Grasas", n:"Perfect Pore", b:"Reduce la apariencia de poros dilatados y regula el brillo.", a:"Pore Away™, Irgasan", p:"Pomo 70 gr"},
{c:"Pieles Grasas", n:"Loción Secante", b:"Facilita la desaparición de imperfecciones y controla el exceso de oleosidad.", a:"Nicotinamida, Alcanfor, Azufre, Óxido de zinc", p:"Frasco 70 ml"},
{c:"Pieles Grasas", n:"Loción Astringente", b:"Elimina restos de maquillaje y contaminantes cutáneos. Ideal para pieles sensibles.", a:"Nicotinamida, Regaliz, Hamamelis, Boswelia", p:"Frasco 100 ml"},
{c:"Pieles Grasas", n:"Loción Astringente", s:"con Nicotinamida", b:"Sebonormalizante, combate enrojecimiento y prepara la piel.", a:"Nicotinamida, Regaliz, Cloruro de Benzalconio", p:"Frascos 100 / 250 / 500 ml"},
{c:"Pieles Grasas", n:"Emulsión Aqua Pore", b:"Restablece el equilibrio hídrico en pieles grasas y seborreicas.", a:"Aquaxyl™, Hydrovance™, Malva, Regaliz, Tilo", p:"Frascos 100 / 235 ml"},
{c:"Pieles Grasas", n:"Máscara Secativa y Reguladora", b:"Purifica la piel y forma un escudo contra el acné.", a:"Bentonita, Nicotinamida, Azufre, Manzanilla", p:"Potes 180 / 280 gr"},
{c:"Pieles Grasas", n:"Loción Antibacterial", s:"sin acción terapéutica", b:"Limpia profundamente los poros y ayuda a regular la oleosidad.", a:"Urea, Regaliz, Hamamelis, Nicotinamida", p:"Frasco 250 ml"},
{c:"Pieles Grasas", n:"Acné III", b:"Reduce el enrojecimiento, regula el sebo y controla la microflora bacteriana.", a:"Nicotinamida, Oligovita™, Cytobiol™ IRIS A2", p:"Frasco 70 ml"},
{c:"Pieles Grasas", n:"Loción Perfect Pore", s:"con Ácido Salicílico", b:"Sebonormalizante para pieles con oleosidad, brillo extremo y acné.", a:"Cytobiol™ Iris A2, Alfabisabolol, Ácido Salicílico", p:"Frascos 100 y 250 ml"},

// RENOVACIÓN CELULAR
{c:"Renovación Celular", n:"Dermoaclarante", b:"Retarda y previene la formación de manchas cutáneas.", a:"Ácido glicólico, ácido mandélico, Uva Ursi", p:"Pomo 12 gr"},
{c:"Renovación Celular", n:"Loción Glico 40", b:"Loción ácida microdescamante. Atenúa arrugas y acelera la renovación del SC.", a:"Ácido Glicólico, Glicolato de Amonio", p:"Frasco 70 gr", pro:true},
{c:"Renovación Celular", n:"Gel Plus", s:"con Ácido Mandélico y Uva Ursi", b:"Despierta la juventud cutánea, elimina células muertas, aclara máculas.", a:"Ácidos Salicílico, Mandélico, Cítrico, Glicólico, Láctico", p:"Frasco 70 ml"},
{c:"Renovación Celular", n:"Renovador Celular α+β", b:"Mejora arrugas y surcos generando un aspecto joven y luminoso.", a:"Ácido Glicólico y Salicílico, Aloe Vera, Regaliz", p:"Pote 250 gr", pro:true},
{c:"Renovación Celular", n:"Peeling Bio Enzimático", b:"Imita la descamación de las pieles jóvenes, efecto exfoliante progresivo.", a:"Perfection Péptide P3™, Extracto Frutal de AHA's", p:"Pote 160 gr"},
{c:"Renovación Celular", n:"Crema Renovadora", s:"con Ácido Salicílico", b:"Repara la piel rugosa, opaca y con pigmentación desigual.", a:"Ácido Salicílico y Glicólico, Arándano, Ácido Hialurónico", p:"Pomo 70 gr"},
{c:"Renovación Celular", n:"Glico 20", b:"Mejora la renovación y humectación natural, actúa sobre el enrojecimiento.", a:"Ácido Glicólico, Aloe Vera", p:"Pomo 70 gr"},
{c:"Renovación Celular", n:"Gel", s:"con Aha's", b:"Facilita una suave renovación de la piel sin enrojecerla.", a:"Aloe Vera, manzanilla, A.H.A", p:"Pomo 70 gr"},
{c:"Renovación Celular", n:"Gel con Ácido Lactobiónico", b:"Mejora el recambio celular natural, excelente tolerancia incluso en pieles sensibles.", a:"Ácido lactobiónico, Gluconolactona", p:"Gotero 20 ml"},
{c:"Renovación Celular", n:"Gel con Ácido Tranexámico y Pantenol", b:"Previene y aclara manchas disminuyendo la síntesis de melanina.", a:"Ácido Tranexámico, Pantenol", p:"Frasco 70 ml"},
{c:"Renovación Celular", n:"Sérum Ácido Mandélico", b:"Acción antiage, unifica el tono y suma luminosidad.", a:"Ácido Mandélico", p:"Gotero 20 ml"},
{c:"Renovación Celular", n:"Sérum Ácido Salicílico", b:"Betahidroxiácido queratolítico para tratamientos de acné y seborrea.", a:"Ácido Salicílico", p:"Gotero 20 ml"},

// CORPORALES
{c:"Corporales", n:"Emulsión Reafirmante Corporal", s:"con Coenzima Q", b:"Mejora la firmeza y densidad de los tejidos, vehiculiza las grasas.", a:"Cafeína, Carnitina, Ubiquinona, Ácido Hialurónico", p:"Frascos 250 / 500 ml"},
{c:"Corporales", n:"Leche Corporal", s:"con Vitamina A", b:"Protectora y revitalizante; indicada para evitar estrías en embarazo y postparto.", a:"Vitamina A, Colágeno Hidrolizado", p:"Frasco 250 ml"},
{c:"Corporales", n:"Gel Modelador Intensivo", b:"Favorece la vehiculización de grasas y toxinas acumuladas.", a:"Cafeína, Carnitina, Centella Asiática, Algas", p:"Frasco 250 ml"},
{c:"Corporales", n:"Shower Gel", s:"con Proteínas y Extractos Vegetales", b:"Limpia, acondiciona y mejora la piel de todo el cuerpo.", a:"Colágeno y Elastina Hidrolizado, Ginkgo Biloba, Centella Asiática", p:"Frasco 250 ml"},
{c:"Corporales", n:"Solución Corporal", s:"con DMAE", b:"Reafirma glúteos, brazos y piernas. Formulada para electroporación.", a:"DMAE", p:"Frasco 235 ml", pro:true},
{c:"Corporales", n:"Termogel", s:"con Mix Vegetal y Silicio Orgánico", b:"Aumenta la circulación y temperatura local, mejora la apariencia de grasas localizadas. Produce hiperemia — no masajear.", a:"Silicio orgánico, Ginkgo Biloba, Centella Asiática", p:"Frasco 250 ml"},
{c:"Corporales", n:"Bruma Integral", s:"con Cafeína y Árnica", b:"Favorece la circulación de retorno y mejora el aspecto de la piel con celulitis.", a:"Castaño de Indias, Árnica, Centella Asiática, Cafeína", p:"Frascos 100 / 250 ml"},
{c:"Corporales", n:"Emulsión Corporal Multitratamiento", b:"Mejora firmeza y densidad de tejidos, reafirma glúteos, brazos y piernas.", a:"EleVastin™, Cafeína, Carnitina", p:"Pote 250 ml"},
{c:"Corporales", n:"Crema Ultra Relajante", b:"Para masajes de relajación y con piedras calientes/frías.", a:"Alcanfor, aceites esenciales de Lavanda, Eucalipto, Romero", p:"Pote 250 gr"},
{c:"Corporales", n:"Crema Corporal", s:"con Chocolate y Fosfatidilcolina", b:"Acción lipolítica rápida, mejora notablemente la celulitis.", a:"Centella Asiática, Chocolate, Guaraná, Cafeína, Carnitina", p:"Pote 480 gr"},
{c:"Corporales", n:"Crema Corporal Multitratamiento", s:"formato gabinete", b:"Mejora firmeza y densidad de los tejidos con maniobras profesionales.", a:"EleVastin™, Cafeína, Carnitina", p:"Pote 480 gr"},
{c:"Corporales", n:"Scrub Corporal Activo", b:"Renueva y rejuvenece, activos específicos para celulitis.", a:"Sílice, Manzanilla, Centella Asiática, Algas", p:"Potes 160 / 250 gr"},
{c:"Corporales", n:"Criogel Reafirmante", b:"Sensación intensa de frío que ayuda a lograr tejidos más firmes.", a:"Ginkgo Biloba, Menta, Mentol, Cafeína, Carnitina", p:"Potes 250 / 450 ml"},
{c:"Corporales", n:"Vital Body Emulsion", b:"Reduce el inflammaging corporal, no deja oleosidad.", a:"Vitamina B12, Pantenol, Niacinamida, Vitamina E", p:"Pote 250 ml"},
{c:"Corporales", n:"Óleo Corporal Dual", b:"Para masajes descontracturantes, de relax y drenaje linfático.", a:"Jojoba, emolientes protectores de la piel, lavanda", p:"Frasco 100 ml"},
{c:"Corporales", n:"Crema Celulitis III", b:"Favorece el drenaje de líquidos y la microcirculación. Reduce el volumen corporal.", a:"Rosa Mosqueta, Jojoba, Almendras, Cafeína, Silanoles", p:"Pote 250 gr"},

// PROTECCIÓN SOLAR
{c:"Protección Solar", n:"Emulsión Protectora FPS 60", s:"con Color", b:"Protección solar extrema con bronceado progresivo suave.", a:"Filtros UVA y UVB, humectantes y emolientes", p:"Pomo 70 gr"},
{c:"Protección Solar", n:"Bálsamo Protector de Labios", b:"Nutre e hidrata los labios, previene la resequedad.", a:"Manteca de Karité, vitamina E", p:"3 gr"},
{c:"Protección Solar", n:"Bálsamo Protector de Labios Cherry", b:"Igual fórmula, con suave color rosa.", a:"Manteca de Karité, vitamina E", p:"3 gr"},
{c:"Protección Solar", n:"Crema Humectante y Protectora", s:"para Piel Sensible", b:"Humecta en profundidad y protege en climas extremos, ideal post peeling.", a:"Alfa bisabolol, Azuleno", p:"Pomo 140 gr"},
{c:"Protección Solar", n:"Filtro Solar Invisible FPS 30", b:"Spray oil free transparente, alta protección UVA/UVB de rápida absorción.", a:"Filtros UVA/UVB, Vitamina E", p:"Frasco 145 ml"},
{c:"Protección Solar", n:"Filtro Solar Invisible FPS 50", b:"Spray oil free transparente, alta protección UVA/UVB inmediata.", a:"Filtros UVA/UVB, Vitamina E", p:"Frasco 145 ml"},
{c:"Protección Solar", n:"Autobronceante Activador", b:"Bronceado natural, gradual y duradero en pocas horas.", a:"DHA, Melanobronze, Aloe Vera, Vitamina E, Eritrulosa", p:"Frasco 145 ml"},
{c:"Protección Solar", n:"Spray Post Solar", b:"Efecto calmante, alivia el enrojecimiento e hidrata tras el sol.", a:"Alfa Bisabolol, Vitamina E, Aloe Vera, Ceramidas", p:"Frasco 15 ml"},
{c:"Protección Solar", n:"Emulsión Protectora FPS 34", b:"Protección UVA/UVB para pieles moderadamente sensibles al sol.", a:"Filtros UVA y UVB", p:"Frasco 130 ml"},
{c:"Protección Solar", n:"Emulsión Protectora FPS 21", b:"Protección UVA/UVB para pieles menos sensibles al sol.", a:"Filtros UVA y UVB", p:"Frasco 130 ml"},
{c:"Protección Solar", n:"Ultra Fluido FPS 60", b:"Alta protección solar, Oil Control, no deja residuo. Para todo tipo de piel.", a:"Vitamina E, Alfabisabolol, filtros solares", p:"Frasco 60 ml"},

// CAPILARES
{c:"Capilares", n:"Bioactivador Capilar", b:"Favorece el crecimiento del cabello, reactiva las células madre del folículo.", a:"Redensyl™, Biotina, Pantenol", p:"Frasco 100 ml"},
{c:"Capilares", n:"Ampollas Control Caída", b:"Previene la caída, aumenta grosor y volumen del cabello.", a:"HGS (Kopexil), Biotina, extractos de Manzana y Ortiga", p:"5 ampollas x 10 ml"},
{c:"Capilares", n:"Shampoo Biocauterizante", b:"Repara la queratina y colágeno perdidos en procesos químicos como alisados.", a:"Aminoácidos específicos, Fitoqueratina, Aceite de Argán", p:"Frasco 200 ml"},
{c:"Capilares", n:"Shampoo Sebonormalizante", s:"con Tea Tree Oil", b:"Equilibra la oleosidad del cuero cabelludo graso y seborreico.", a:"Tea tree oil, Queratina, Colágeno", p:"Frasco 200 ml"},
{c:"Capilares", n:"Shampoo para la Caída", b:"Mejora la caída y fortaleza del cabello.", a:"HGS, Ortiga, Ginkgo Biloba, Queratina", p:"Frasco 200 ml"},
{c:"Capilares", n:"Shampoo Antiage", b:"Protege, nutre y repara el cabello dañado por sol, planchita y tinturas.", a:"Bamboo, fitoesfingosina, ceramidas, queratina", p:"Frasco 200 ml"},

// MANOS Y PIES
{c:"Manos y Pies", n:"Crema Antiage para Manos", s:"con Vitaminas", b:"Recupera, mantiene y protege la piel de manos, brazos y codos.", a:"Vitamina A y E, Aloe Vera, Glicerina", p:"Pomo 70 / 250 gr"},
{c:"Manos y Pies", n:"Crema para Manos", s:"con Ácido Hialurónico", b:"Humecta, suaviza y regenera la piel.", a:"Queratina, Aloe Vera, Colágeno, Ácido Hialurónico", p:"Pomo 70 gr"},
{c:"Manos y Pies", n:"Crema Deportiva y Restauradora para Pies", b:"Mejora la textura y suavidad de la piel de los pies, reduce sequedad.", a:"Urea, Lúpulo, Caléndula, Lanolina, Vitamina A", p:"Pote 160 gr"},
{c:"Manos y Pies", n:"Crema Hidratante Perfumada F3", b:"Humecta, suaviza y perfuma la piel con fragancia floral oriental.", a:"Queratina, Aloe Vera, Colágeno, Ácido Hialurónico", p:"Pomo 70 gr"},
{c:"Manos y Pies", n:"Ablandador Pédico", b:"Ablanda las durezas epidérmicas para el trabajo profesional de pedicuría.", a:"Irgasam, Romero, Hidróxido de sodio", p:"Frasco 500 ml"},

// CUIDADOS MASCULINOS
{c:"Cuidados Masculinos", n:"Bálsamo After Shave", b:"Hidrata, repara y descongestiona la piel luego del afeitado.", a:"Ácido hialurónico, Aloe Vera, Colágeno, Manteca de Karité", p:"Pomo 70 gr"},
{c:"Cuidados Masculinos", n:"Emulsión Energía Vital", b:"Protege la piel de las agresiones del medio, atenúa arrugas superficiales.", a:"Colágeno, Aloe Vera, Manzanilla, Ginseng", p:"Frasco 70 ml"},
{c:"Cuidados Masculinos", n:"Sérum Reparador Antiage", b:"Mejora la expresión y el cansancio del contorno de ojos.", a:"Manteca de Karité, Colágeno hidrolizado, Ácido Hialurónico", p:"Frasco 15 ml"},

// SENSORIAL
{c:"Sensorial", n:"Emulsión Hidratante Enigmática", s:"Mango y Miel", b:"Hidratación extrema, piel aterciopelada con destellos plateados.", a:"Hidrovance™, Ginseng, Jojoba, Mimosa", p:"Frasco 240 ml"},
{c:"Sensorial", n:"Emulsión Hidratante Ilusión", s:"Frutos del Bosque Patagónico", b:"Hidratación extrema con sensación de frescura durante el masaje.", a:"Hidrovance™, Ginseng, Jojoba, Mimosa", p:"Frasco 240 ml"},
{c:"Sensorial", n:"Emulsión Hidratante Salvaje", s:"fragancia frutal", b:"Hidratación extrema, piel aterciopelada, sensación de frescura y elasticidad.", a:"Hidrovance™, Ginseng, Jojoba, Mimosa", p:"Frasco 240 ml"},
{c:"Sensorial", n:"Emulsión Hidratante Fresca", s:"lilas, gardenias y vainilla", b:"Hidratación extrema, excelente sensorial y piel aterciopelada.", a:"Hidrovance™, Ginseng, Jojoba, Mimosa", p:"Frasco 240 ml"},
{c:"Sensorial", n:"Body Splash Vainilla de Tahití", b:"Aroma delicado y sensual de larga durabilidad.", a:"Jazmín, muguet, vainilla de Tahití, ámbar, sándalo", p:"Frasco 125 ml"},
{c:"Sensorial", n:"Body Splash Azúcar de Coco", b:"Aromas juveniles y deslumbrantes.", a:"Coco, lirios, azúcar, ámbar, vainilla", p:"Frasco 125 ml"},
{c:"Sensorial", n:"Body Splash Flor de Tiare", b:"Aroma delicado y enérgico del universo femenino.", a:"Papaya, Flor de Tiare, azahar, rosas blancas, vainilla", p:"Frasco 125 ml"},
{c:"Sensorial", n:"Aceite Esencial Eucalipto", b:"Aroma fresco y penetrante para tratamientos cosméticos o hidroterapia.", a:"Aceite Esencial Eucalipto", p:"Gotero 10 ml"},
{c:"Sensorial", n:"Aceite Esencial Tea Tree", b:"Aliado en pieles con acné, normalizador de la microflora cutánea.", a:"Aceite Esencial Tea Tree Oil", p:"Gotero 10 ml"},
{c:"Sensorial", n:"Aceite Esencial Lavanda", b:"Ayuda a nivelar el estrés y la ansiedad, promueve la relajación.", a:"Aceite de Lavanda", p:"Gotero 10 ml"},
{c:"Sensorial", n:"Aceite Esencial Romero", b:"Ayuda a mejorar la concentración y la memoria.", a:"Aceite Esencial Romero", p:"Gotero 10 ml"},
{c:"Sensorial", n:"Aceite Esencial Sumun 31", b:"Blend purificante, tonificante y relajante de varios aceites esenciales.", a:"Blend de aromas (tea tree, menta, eucalipto, pino, anís)", p:"Gotero 10 ml"},

// FRAGANCIAS
{c:"Fragancias", n:"Fragancia Femenina 1", s:"F1", b:"Dulce y envolvente, con pimienta rosa y flor de naranjo. Fondo de benjuí, vainilla y habas Tonka.", p:"Frasco 55 ml"},
{c:"Fragancias", n:"Fragancia Femenina 2", s:"F2", b:"Cítrica y sensual, con maracuyá, muguet, jazmín y gardenia. Fondo amaderado.", p:"Frasco 55 ml"},
{c:"Fragancias", n:"Fragancia Femenina 3", s:"F3", b:"Floral oriental, rosa blanca y búlgara, caramelo, praliné y fondo de ámbar e iris.", p:"Frasco 55 ml"},
{c:"Fragancias", n:"Fragancia Masculina 1", s:"M1", b:"Fresca y envolvente, notas cítricas y marinas. Fondo de madera de Guaiac y ámbar gris.", p:"Frasco 55 ml"},
{c:"Fragancias", n:"Fragancia Masculina 2", s:"M2", b:"Perdurable y enérgica, notas florales y amaderadas. Fondo de cedro, sándalo y vainilla.", p:"Frasco 55 ml"},

// TEENS
{c:"Teens", n:"My Cleaner Gel Exfoliante", b:"Limpia y mejora la textura de la piel sin agredir. Apto para pieles sensibles.", a:"Polímero abrasivo, extractos frutales", p:"Pomo 140 gr"},
{c:"Teens", n:"Stop Estrías Emulgel", b:"Rehidrata la piel mejorando su firmeza, reduce y previene estrías.", a:"Extracto Oleoso de Almendras, Vitamina E, Rosa Mosqueta", p:"Frasco 250 ml"},
{c:"Teens", n:"Loción Matificante", b:"Regula el brillo del rostro, ideal para pieles grasas, mixtas o seborreicas.", a:"Pore Away, Propilenglicol", p:"Frasco 100 / 250 ml"},

// LACA BEAUTY
{c:"Laca Beauty", n:"Crema Light", b:"Elimina restos de maquillaje e impurezas sin masaje excesivo.", a:"Limpiadores dérmicos, Manzanilla", p:"Pote 45 g"},
{c:"Laca Beauty", n:"Sérum Cremoso", b:"Hidratación y humectación profunda, mejora la firmeza del óvalo facial.", a:"Manzanilla, Vitamina E, Colágeno, Elastina", p:"Pote 45 g"},
{c:"Laca Beauty", n:"Mousse de Día", b:"Hidratación diaria eficaz, mantiene la piel lozana y turgente.", a:"Vitaminas A y E, Urea, Manzanilla", p:"Pote 45 g"},
{c:"Laca Beauty", n:"Agua Facial", b:"Calma, humecta y refresca la piel con rasgos enrojecidos.", a:"Manzanilla, Lavanda, aceites esenciales purificantes", p:"Frasco 100 ml"},
{c:"Laca Beauty", n:"Leche Corporal", b:"Acción protectora, regeneradora y revitalizante de los tejidos.", a:"Vitamina A, Vitamina E, Algas Marinas, Centella Asiática", p:"Frasco 200 ml"},

];
